version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: cp .env.prod .env
      - run: ls -a
      - run: npm run deploy
      - run: echo "export COMMIT_MESSAGE=\"$(git log --format=oneline -n 1 $CIRCLE_SHA1)\"" >> ~/.bashrc
      - run: echo $COMMIT_MESSAGE
      - slack/status:
          webhook: ${SLACK_WEBHOOK}
          success_message: >
            ðŸŽ‰ mypass frontend has deployed!
            commit: $COMMIT_MESSAGE
          failure_message: >
            ðŸ”´ mypass frontend deploy has failed!
            commit: $COMMIT_MESSAGE
          only_for_branches: master
workflows:
  build-and-test:
    jobs:
      - build
  version: 2.1
