version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: cp .env.prod .env
      - run: ls -a
      - run: npm run deploy
      - slack/status:
          webhook: ${SLACK_WEBHOOK}
          success_message: >
            mypass frontend has deployed!
          failure_message: >
            mypass frontend deploy has failed!
          only_for_branches: main
workflows:
  version: 2.0
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
